/*
 * BEGIN OpenSolaris section
 *   This is an unstable interface; changes may be made
 *   without notice.
 * END OpenSolaris section
 */

/* : : generated by proto : : */

#if !defined(__PROTO__)
#include <prototyped.h>
#endif
#if !defined(__LINKAGE__)
#define __LINKAGE__		/* 2004-08-11 transition */
#endif
#define _AST_VERSION	20100102L
